language: csharp
solution: Launchpad.sln
before_install:
  - sudo nuget update -self
install:
  - sudo apt-get install -y gtk-sharp2 libwebkit-cil-dev libwebkit1.1-cil libwebkitgtk-dev
  - nuget restore Launchpad.sln -Verbosity detailed
script:
    - xbuild /p:Configuration=Release Launchpad.Launcher/Launchpad.Launcher.csproj
